spring:
  application:
    name: item_service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8070/}"

  datasource:
    url: jdbc:h2:mem:item_db
    driver-class-name: org.h2.Driver
    username: sa
    password: ''

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 6MB

file:
  upload-dir: ${FILE_UPLOAD_DIR:uploads/images}

