server:
  port: 8081

spring:
  application:
    name: bidding_service

  datasource:
    url: jdbc:h2:mem:test_db
    driver-class-name: org.h2.Driver
    username: da
    password: ''

  # Example configuration for PostgreSQL in production/docker:
  # datasource:
  #   url: jdbc:postgresql://localhost:5432/bidding_db
  #   driver-class-name: org.postgresql.Driver
  #   username: postgres
  #   password: password

  h2:
    console:
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8071/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
